spring:
  application:
    name: eureka-server
  config:
    activate:
      on-profile: local-dev
#  profiles:
#    active: local-dev

server:
  port: 8761
  shutdown: graceful

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${eureka.host:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0

---
spring:
  application:
    name: eureka-server
  config:
    activate:
      on-profile: docker-dev

server:
  port: 8761
  shutdown: graceful

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${eureka.host:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0