server:
  port: 9001
  shutdown: graceful
#  servlet:
#    context-path: "/demo-app"

spring:
  application:
    name: demo-app
  config:
    activate:
      on-profile: local-dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    discovery:
      enabled: true
      client:
        health-indicator:
          enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: demoappuser
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.company.demo_app: DEBUG

---
server:
  port: 9001
  shutdown: graceful

spring:
  application:
    name: demo-app
  config:
    activate:
      on-profile: docker-dev
  cloud:
    discovery:
      enabled: true
      client:
        health-indicator:
          enabled: true
  datasource:
    url: jdbc:postgresql://postgres_db:5432/postgres
    username: demoappuser
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://${eureka.host:eureka-server}:${eureka.port:8761}/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.company.demo_app: DEBUG

